
services:
  user_microservice_v1:
    build:
      context: ./user_microservice
    environment:
      - MONGO_URI=${MONGO_URI}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "5001:5001"
    networks:
      - microservice_network
networks:
  microservice_network:
    driver: bridge
