version: '3.8'

services:
  user_microservice:
    build:
      context: ./user_microservice
    container_name: user_microservice
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/my_assignment_db
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
