version: '3.8'

services:
  user_microservice:
    build:
      context: ./user_microservice
    container_name: user_microservice
    ports:
      - "5001:5001"  # Maps to host IP's 5001
    environment:
      - PYTHONUNBUFFERED=1
      - PIP_INDEX_URL=https://pypi.org/simple/
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
